-- return {
--   {
--     'kevinhwang91/nvim-ufo',
--     requires = 'kevinhwang91/promise-async',
--     cond = {
--       Keys('n', 'zR'),
--       Keys('n', 'zM'),
--       Event 'UiEnter',
--     },
--     config = function()
--       require 'ufo'.setup({
--         provider_selector = function()
--           return { 'treesitter', 'indent' }
--         end
--       })
--       vim.keymap.set('n', 'zR', require('ufo').openAllFolds)
--       vim.keymap.set('n', 'zM', require('ufo').closeAllFolds)
--     end,
--   }
-- }
