-- -- local cmd = require 'pckr.loader.cmd'
-- -- local keys = require 'pckr.loader.keys'
-- local event = require 'pckr.loader.event'

-- return {
--   {
--     'VioletJewel/vimterm.nvim',
--     cond = event 'UIEnter',
--     config = function() require 'vimterm'.setup() end,
--   },
-- }
